# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('goodName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('categoryName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('categoryIcon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('misc', models.CharField(blank=True, max_length=256)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('priority', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('catastrophy', models.CharField(max_length=128)),
                ('postalCode', models.CharField(max_length=32)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.GoodCategory')),
                ('goodName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('misc', models.CharField(blank=True, max_length=256)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('postalCode', models.CharField(max_length=32)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.GoodCategory')),
                ('goodName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('postalCode', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.User'),
        ),
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.User'),
        ),
        migrations.AddField(
            model_name='good',
            name='categoryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tim_app.GoodCategory'),
        ),
    ]
