# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='categoryName',
        ),
        migrations.RemoveField(
            model_name='request',
            name='categoryName',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='categoryName',
        ),
        migrations.DeleteModel(
            name='GoodCategory',
        ),
    ]
