# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='radius',
            field=models.IntegerField(default=0),
        ),
    ]
