# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0002_auto_20160627_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
