# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0002_auto_20160529_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='postalCode',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='postalCode',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postalCode',
            new_name='phoneNr',
        ),
        migrations.RemoveField(
            model_name='request',
            name='catastrophy',
        ),
        migrations.AddField(
            model_name='request',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='request',
            name='radius',
            field=models.CharField(default=5, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='radius',
            field=models.CharField(default=5, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='radius',
            field=models.CharField(default=5, max_length=32),
            preserve_default=False,
        ),
    ]
