# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0003_user_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
    ]
